### ISSUE TITLE
Error starting remapping example scene (and others)

### ISSUE THREAD

**Issue by hatmix** [godotneers/G.U.I.D.E#3]
`Invalid access to property or key 'mouse' on a base object of type 'Resource (GUIDEInputKey)'`

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 32.0.15.6636) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

Steps to reproduce:
1. Checkout main branch -- commit f0f7def14670cf157834d7fd24b4af2f6bd72dd0 (HEAD -> main, tag: v0.0.3, origin/main, origin/HEAD)
2. Open Godot project
3. Enable G.U.I.D.E. plugin
4. Reload project
5. Open `res://guide_examples/remapping/remapping.tscn` (I tested a few others and got same error, but not all)
6. Select Run Current Scene (F6)

I don't see a straightforward way to copy the full stacktrace, so here is a screenshot in case it's helpful :(

![image](https://github.com/user-attachments/assets/f217c79c-595a-4453-8c73-76a8ca9e0681)

The error occurs in `guide_input_any.gd` line 39:
```
func is_same_as(other:GUIDEInput) -> bool:
	return other is GUIDEInput and \
-->		other.mouse == mouse and \
		other.joy == joy and \
		other.keyboard == keyboard 
```

In this case `other` is an instance of `GUIDEInputKey` which does not appear to have mouse, job, or keyboard properties.

G.U.I.D.E. is a very exciting addon and thanks for sharing such cool stuff!

**Comment by derkork** [comment]
Hmm very strange I thought I had fixed this one already but apparently I didn't commit it. Thanks for taking the time to report it. I'll release 0.0.4 with the fix.
